## Crear X, Y

In [79]:
import pandas as pd
import numpy as np

data = pd.read_csv('data/petrol_consumption.csv', delimiter='\t', header=0 ,dtype=np.float64)
data = data.values

set_x = data[:,0:-1]
set_y = data[:,-1]

print(set_x)
print(set_y)


[[9.0000e+00 3.5710e+03 1.9760e+03 5.2500e-01]
 [9.0000e+00 4.0920e+03 1.2500e+03 5.7200e-01]
 [9.0000e+00 3.8650e+03 1.5860e+03 5.8000e-01]
 [7.5000e+00 4.8700e+03 2.3510e+03 5.2900e-01]
 [8.0000e+00 4.3990e+03 4.3100e+02 5.4400e-01]
 [1.0000e+01 5.3420e+03 1.3330e+03 5.7100e-01]
 [8.0000e+00 5.3190e+03 1.1868e+04 4.5100e-01]
 [8.0000e+00 5.1260e+03 2.1380e+03 5.5300e-01]
 [8.0000e+00 4.4470e+03 8.5770e+03 5.2900e-01]
 [7.0000e+00 4.5120e+03 8.5070e+03 5.5200e-01]
 [8.0000e+00 4.3910e+03 5.9390e+03 5.3000e-01]
 [7.5000e+00 5.1260e+03 1.4186e+04 5.2500e-01]
 [7.0000e+00 4.8170e+03 6.9300e+03 5.7400e-01]
 [7.0000e+00 4.2070e+03 6.5800e+03 5.4500e-01]
 [7.0000e+00 4.3320e+03 8.1590e+03 6.0800e-01]
 [7.0000e+00 4.3180e+03 1.0340e+04 5.8600e-01]
 [7.0000e+00 4.2060e+03 8.5080e+03 5.7200e-01]
 [7.0000e+00 3.7180e+03 4.7250e+03 5.4000e-01]
 [7.0000e+00 4.7160e+03 5.9150e+03 7.2400e-01]
 [8.5000e+00 4.3410e+03 6.0100e+03 6.7700e-01]
 [7.0000e+00 4.5930e+03 7.8340e+03 6.6300e-01]
 [8.0000e+00 

## Normalizar X, Y

In [80]:
def norm(arr):
    mean = np.mean(arr,axis=0)
    std = np.std(arr, axis=0)
    for i in range(0, arr.shape[0]):
        arr[i] = np.true_divide(arr[i] - mean, std)
    return arr

set_x = norm(set_x)
set_y = norm(set_y)
print(set_x)
print(set_y)

[[ 1.4154413  -1.18184136 -1.03892124 -0.8259031 ]
 [ 1.4154413  -0.26396904 -1.24905478  0.03036408]
 [ 1.4154413  -0.66388654 -1.1518029   0.17611169]
 [-0.17892312  1.10667332 -0.93038119 -0.7530293 ]
 [ 0.35253169  0.27688855 -1.48610625 -0.47975254]
 [ 2.47835091  1.93821984 -1.22503125  0.01214563]
 [ 0.35253169  1.89769956  1.82422057 -2.17406847]
 [ 0.35253169  1.5576816  -0.99203194 -0.31578648]
 [ 0.35253169  0.3614526   0.87167309 -0.7530293 ]
 [-0.71037792  0.47596642  0.85141228 -0.33400493]
 [ 0.35253169  0.26279454  0.10813001 -0.73481085]
 [-0.17892312  1.5576816   2.4951428  -0.8259031 ]
 [-0.71037792  1.01330051  0.39496518  0.06680099]
 [-0.71037792 -0.06136766  0.29366114 -0.46153409]
 [-0.71037792  0.15885122  0.75068711  0.68622832]
 [-0.71037792  0.13418671  1.38195604  0.2854224 ]
 [-0.71037792 -0.06312941  0.85170172  0.03036408]
 [-0.71037792 -0.92286395 -0.24325031 -0.55262634]
 [-0.71037792  0.83536365  0.10118345  2.79956861]
 [ 0.88398649  0.17470698  0.12

## Dividir en train, test

In [81]:
limit = int(0.7*len(set_x))
train_x , test_x = set_x[:limit,:], set_x[limit:, :]
train_y , test_y = set_y[:limit], set_y[limit:] 

np.savetxt('data/1_train_x.csv', train_x, delimiter=',')
np.savetxt('data/1_train_y.csv', train_y, delimiter=',')

np.savetxt('data/1_test_x.csv', test_x, delimiter=',')
np.savetxt('data/1_test_y.csv', test_y, delimiter=',')


In [4]:
limit = int(len(array1)*0.7)
array1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
array2 = np.array([1,2,3,4,5,6])
trainx , testx = array1[:limit,:], array1[limit:, :]
trainy , testy = array2[:limit], array2[limit:]
print(trainx)
print(testx)
print(trainy)
print(testy)

NameError: name 'array1' is not defined

# Experimento 2 - Generación de energía solar

In [111]:
import pandas as pd
import numpy as np
data = pd.read_csv('data/solar_generation.csv', delimiter=',', header=0)

# Obtener datos de una sola planta y un solo día
id_planta = '1BY6WEcLGh8j5v7'
data = data[data.SOURCE_KEY == id_planta]
del data['DAILY_YIELD']

# Convertir formato de hora en número(minutos)
for i, row in data.iterrows():
    ifor_val = row[0][10:]
    val = int(ifor_val[0:3])*60 + int(ifor_val[4:])
    # print(ifor_val, val)
    data.at[i,'DATE_TIME'] = val

# Mezclar filas
data=data.sample(frac=1).reset_index(drop=True)

print(data.columns)

# Eliminar columna innecesaria
del data['SOURCE_KEY']
del data['PLANT_ID']
print(data.columns)
data['DATE_TIME'] = data['DATE_TIME'].astype(float)
    
# Separar en X, Y
set_x = data
set_y = data['TOTAL_YIELD']
del set_x['TOTAL_YIELD']

# Normalizar
def norm(arr):
    mean = np.mean(arr,axis=0)
    std = np.std(arr, axis=0)
    for i in range(0, arr.shape[0]):
        arr[i] = np.true_divide(arr[i] - mean, std)
    return arr

# print(set_x.values)
# print(set_y.values)
set_x = norm(set_x.values)
set_y = norm(set_y.values)


print(set_x.shape)
print(set_y.shape)

limit = int(len(data.values)*0.7)

train_x, test_x = set_x[:limit, :], set_x[limit:, :]
train_y, test_y = set_y[:limit], set_y[limit:]
print(train_x.shape, test_x.shape)
print(train_y.shape, test_y.shape)

np.savetxt('data/2_train_x.csv', train_x, delimiter=',')
np.savetxt('data/2_train_y.csv', train_y, delimiter=',')

np.savetxt('data/2_test_x.csv', test_x, delimiter=',')
np.savetxt('data/2_test_y.csv', test_y, delimiter=',')



Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'TOTAL_YIELD'],
      dtype='object')
Index(['DATE_TIME', 'DC_POWER', 'AC_POWER', 'TOTAL_YIELD'], dtype='object')
(93, 3)
(93,)
(65, 3) (28, 3)
(65,) (28,)
